# Generated by Django 5.1.3 on 2024-11-28 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="old_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
