# Generated by Django 5.1.3 on 2024-11-28 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_old_id_alter_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="old_id",
        ),
    ]
